-- Datos de ejemplo
SET NAMES utf8mb4;

INSERT INTO categories (id, type, name, slug, description, sort_order) VALUES
(1, 'bike', 'Carretera', 'carretera', 'Ligereza y aerodinámica para devorar kilómetros de asfalto.', 1),
(2, 'bike', 'Gravel', 'gravel', 'Un cuadro, todos los caminos. Asfalto, pista y aventura.', 2),
(3, 'bike', 'Montaña', 'montana', 'Suspensión, tracción y control para los senderos más técnicos.', 3),
(4, 'bike', 'Urbana', 'urbana', 'Estilo y practicidad para moverte por la ciudad.', 4),
(5, 'bike', 'Eléctrica', 'electrica', 'Asistencia inteligente para llegar más lejos.', 5),
(6, 'accessory', 'Cascos', 'cascos', 'Protección certificada y ventilación.', 6),
(7, 'accessory', 'Ropa', 'ropa', 'Maillots, culottes y chaquetas técnicas.', 7),
(8, 'accessory', 'Luces', 'luces', 'Ve y hazte ver de día y de noche.', 8),
(9, 'accessory', 'Bolsas', 'bolsas', 'Bikepacking y transporte diario.', 9),
(10,'accessory', 'Componentes', 'componentes', 'Ruedas, sillines, pedales y más.', 10);

INSERT INTO products (id, category_id, name, slug, short_desc, description, specs, price, compare_price, stock, image, featured) VALUES
(1, 1, 'Aero R1 Carbon', 'aero-r1-carbon',
 'Cuadro de carbono aerodinámico con grupo electrónico de 12 velocidades.',
 'La Aero R1 es nuestra bici de carretera más rápida. Cuadro monocasco de carbono de alto módulo, cableado totalmente integrado y geometría racing para quienes buscan cada segundo.',
 '{"Cuadro":"Carbono alto módulo","Grupo":"Electrónico 2x12","Frenos":"Disco hidráulico","Ruedas":"Carbono 50 mm","Peso":"7,2 kg"}',
 4299.00, 4799.00, 0, 'assets/img/products/aero-r1-carbon.svg', 1),
(2, 1, 'Endurance E3', 'endurance-e3',
 'Confort y rendimiento para largas distancias.',
 'Geometría endurance con tubo de dirección más alto y holgura para cubiertas de 32 mm. Perfecta para marchas cicloturistas y salidas largas.',
 '{"Cuadro":"Aluminio 6061 hidroformado","Horquilla":"Carbono","Grupo":"Mecánico 2x11","Frenos":"Disco hidráulico","Peso":"9,1 kg"}',
 1649.00, NULL, 0, 'assets/img/products/endurance-e3.svg', 0),
(3, 2, 'Nomad GX', 'nomad-gx',
 'Gravel de carbono lista para bikepacking.',
 'Múltiples anclajes para bolsas y portabidones, holgura para 45 mm y geometría estable. Nomad GX está pensada para salir el viernes y volver el domingo.',
 '{"Cuadro":"Carbono","Grupo":"1x12 gravel","Neumáticos":"700x45c","Anclajes":"Horquilla y tubo superior","Peso":"8,6 kg"}',
 2899.00, NULL, 0, 'assets/img/products/nomad-gx.svg', 1),
(4, 2, 'Trail Gravel AL', 'trail-gravel-al',
 'La puerta de entrada al gravel sin renunciar a nada.',
 'Cuadro de aluminio, frenos de disco y una transmisión fiable. La mejor relación calidad-precio para empezar a explorar.',
 '{"Cuadro":"Aluminio","Grupo":"2x10","Frenos":"Disco mecánico","Neumáticos":"700x40c","Peso":"10,4 kg"}',
 1199.00, 1349.00, 0, 'assets/img/products/trail-gravel-al.svg', 0),
(5, 3, 'Ridge 140 Trail', 'ridge-140-trail',
 'Doble suspensión de 140 mm para trail y all-mountain.',
 'Cinemática optimizada, tija telescópica y ruedas de 29". Sube con eficiencia y baja con confianza.',
 '{"Suspensión":"140 / 130 mm","Ruedas":"29\\"","Grupo":"1x12","Tija":"Telescópica 170 mm","Peso":"14,2 kg"}',
 3599.00, NULL, 0, 'assets/img/products/ridge-140-trail.svg', 1),
(6, 3, 'Summit HT', 'summit-ht',
 'Rígida de XC ligera y reactiva.',
 'Hardtail de competición con horquilla de 100 mm y geometría moderna para rodar rápido en cualquier circuito.',
 '{"Suspensión":"Horquilla 100 mm","Ruedas":"29\\"","Grupo":"1x12","Frenos":"Disco hidráulico","Peso":"11,3 kg"}',
 1499.00, NULL, 0, 'assets/img/products/summit-ht.svg', 0),
(7, 4, 'City Classic', 'city-classic',
 'Urbana de líneas clásicas con cambio interno.',
 'Guardabarros, portabultos y luces integradas. Todo lo que necesitas para tu día a día en la ciudad.',
 '{"Cuadro":"Acero cromoly","Cambio":"Interno 7 velocidades","Frenos":"Rodillo","Extras":"Portabultos, luces dinamo","Peso":"14,8 kg"}',
 749.00, NULL, 0, 'assets/img/products/city-classic.svg', 0),
(8, 4, 'Fixie Street', 'fixie-street',
 'Minimalista, ligera y sin complicaciones.',
 'Piñón fijo / libre reversible y un diseño limpio para moverse con estilo.',
 '{"Cuadro":"Aluminio","Transmisión":"Single speed / fixie","Frenos":"Herradura","Peso":"9,4 kg"}',
 499.00, 579.00, 0, 'assets/img/products/fixie-street.svg', 0),
(9, 5, 'E-Urban Volt', 'e-urban-volt',
 'Eléctrica urbana con 90 km de autonomía.',
 'Motor central de 250 W, batería integrada de 540 Wh y correa de carbono sin mantenimiento.',
 '{"Motor":"Central 250 W · 65 Nm","Batería":"540 Wh integrada","Autonomía":"Hasta 90 km","Transmisión":"Correa de carbono","Peso":"21 kg"}',
 2799.00, NULL, 0, 'assets/img/products/e-urban-volt.svg', 1),
(10, 5, 'E-Trail Power', 'e-trail-power',
 'E-MTB de 150 mm para no poner límites.',
 'Motor de 85 Nm y batería de 720 Wh para rutas de montaña sin fin.',
 '{"Motor":"Central 250 W · 85 Nm","Batería":"720 Wh","Suspensión":"150 / 140 mm","Ruedas":"29\\" / 27,5\\" mullet","Peso":"23,5 kg"}',
 5299.00, NULL, 0, 'assets/img/products/e-trail-power.svg', 0),

(11, 6, 'Casco Aero Pro', 'casco-aero-pro',
 'Casco de carretera aerodinámico con tecnología MIPS.',
 'Carcasa aerodinámica, 14 ventilaciones y sistema MIPS de protección rotacional.',
 '{"Certificación":"EN 1078","Sistema":"MIPS","Peso":"260 g"}',
 149.00, NULL, 0, 'assets/img/products/casco-aero-pro.svg', 1),
(12, 6, 'Casco Trail MTB', 'casco-trail-mtb',
 'Protección extendida para montaña.',
 'Mayor cobertura en nuca y sienes, visera ajustable y compatible con gafas.',
 '{"Certificación":"EN 1078","Visera":"Ajustable","Peso":"340 g"}',
 99.00, NULL, 0, 'assets/img/products/casco-trail-mtb.svg', 0),
(13, 7, 'Maillot Team', 'maillot-team',
 'Maillot técnico de manga corta.',
 'Tejido transpirable, corte ajustado y tres bolsillos traseros.',
 '{"Material":"Poliéster reciclado","Bolsillos":"3 + cremallera","Corte":"Race"}',
 69.00, NULL, 0, 'assets/img/products/maillot-team.svg', 1),
(14, 7, 'Culotte Bib Pro', 'culotte-bib-pro',
 'Culotte con tirantes y badana de alta densidad.',
 'Badana para largas distancias y tirantes de malla transpirable.',
 '{"Badana":"Alta densidad","Material":"Lycra compresiva"}',
 99.00, 119.00, 0, 'assets/img/products/culotte-bib-pro.svg', 0),
(15, 8, 'Luz delantera 1200', 'luz-delantera-1200',
 '1200 lúmenes recargables por USB-C.',
 'Seis modos de luz y hasta 20 horas de autonomía.',
 '{"Potencia":"1200 lm","Carga":"USB-C","Autonomía":"Hasta 20 h"}',
 59.00, NULL, 25, 'assets/img/products/luz-delantera-1200.svg', 0),
(16, 8, 'Luz trasera Radar', 'luz-trasera-radar',
 'Luz trasera con detección de vehículos.',
 'Avisa en tu ciclocomputador cuando se acerca un vehículo por detrás.',
 '{"Alcance radar":"140 m","Autonomía":"Hasta 16 h"}',
 189.00, NULL, 12, 'assets/img/products/luz-trasera-radar.svg', 1),
(17, 9, 'Bolsa de sillín 12L', 'bolsa-sillin-12l',
 'Bolsa estanca para bikepacking.',
 'Cierre enrollable, estanca y con arnés estabilizador.',
 '{"Capacidad":"12 L","Material":"Nylon impermeable"}',
 79.00, NULL, 18, 'assets/img/products/bolsa-sillin-12l.svg', 0),
(18, 9, 'Alforja urbana', 'alforja-urbana',
 'Alforja impermeable con asa y bandolera.',
 'Enganche rápido al portabultos y compartimento para portátil.',
 '{"Capacidad":"20 L","Material":"Lona encerada"}',
 89.00, NULL, 10, 'assets/img/products/alforja-urbana.svg', 0),
(19, 10, 'Ruedas Carbon 45', 'ruedas-carbon-45',
 'Juego de ruedas de carbono de 45 mm.',
 'Tubeless ready, bujes de trinquete y solo 1.390 g el par.',
 '{"Perfil":"45 mm","Peso":"1.390 g","Tubeless":"Sí"}',
 1099.00, 1290.00, 6, 'assets/img/products/ruedas-carbon-45.svg', 0),
(20, 10, 'Sillín Comfort Pro', 'sillin-comfort-pro',
 'Sillín con canal central y raíles de titanio.',
 'Diseño ergonómico que reduce la presión en rutas largas.',
 '{"Raíles":"Titanio","Anchos":"143 / 155 mm","Peso":"215 g"}',
 89.00, NULL, 30, 'assets/img/products/sillin-comfort-pro.svg', 0);

-- Tallas para bicicletas y ropa/cascos
INSERT INTO product_variants (product_id, label, stock, sort_order) VALUES
(1,'S',2,1),(1,'M',3,2),(1,'L',2,3),(1,'XL',1,4),
(2,'S',3,1),(2,'M',4,2),(2,'L',4,3),(2,'XL',2,4),
(3,'S',2,1),(3,'M',3,2),(3,'L',3,3),
(4,'S',5,1),(4,'M',6,2),(4,'L',5,3),(4,'XL',2,4),
(5,'M',2,1),(5,'L',3,2),(5,'XL',1,3),
(6,'S',3,1),(6,'M',4,2),(6,'L',3,3),
(7,'Única',8,1),
(8,'M',4,1),(8,'L',4,2),
(9,'M',3,1),(9,'L',3,2),
(10,'M',1,1),(10,'L',2,2),(10,'XL',0,3),
(11,'S',5,1),(11,'M',8,2),(11,'L',5,3),
(12,'M',6,1),(12,'L',6,2),
(13,'S',10,1),(13,'M',15,2),(13,'L',12,3),(13,'XL',6,4),
(14,'S',6,1),(14,'M',10,2),(14,'L',8,3);
